### ISSUE TITLE
Create a setup.cfg

### ISSUE THREAD

**Issue by krp391** [NYU-Devops-orders/orders#19]
**As a** ...
**I need** ...
**So that** ...
**Assumptions:**
* ...
**Acceptance Criteria:**
```
Given ...
When ...
Then ..
```

**Comment by krp391** [comment]
I didn't fill this one out as I am a bit confused on what a setup.cfg does

**Comment by knp319** [comment]
Create a setup.cfg file with all of your nosetests options so that you only have to type nosetests to run the test suite.
