### ISSUE TITLE
Create test case for create order

### ISSUE THREAD

**Issue by krp391** [NYU-Devops-orders/orders#20]
**As a** customer
**I need** to create an order
**So that** I can get products
**Assumptions:**
* - A test fails when code is not available

**Acceptance Criteria:**
```
Given a test case
When they are run
Then proper code is available if it passes the test 
```

**Comment by knp319** [comment]
Start developing by creating the TDD test_xxx.py files that contains your Unit Tests to test your service and model.

**Comment by knp319** [comment]
Write test cases to test your model

**Comment by knp319** [comment]
Write test cases to test your service

**Comment by knp319** [comment]
There should be tests for each of Create, Read, Update, Delete, List, Query, Action, traversing both happy paths and sad paths
Run these tests using nosetest as you develop the code making them all green (passing)
Use the coverage tool to measure your test coverage. Your goal is get it above 95% for full credit.

**Comment by knp319** [comment]
Place your test cases in a ./tests folder.
