### ISSUE TITLE
Create the Order Model

### ISSUE THREAD

**Issue by krp391** [NYU-Devops-orders/orders#21]
**As a** customer
**I need**  to have my orders  about me in a DB
**So that** I can see what I have ordered 
**Assumptions:**
* The model is valid
**Acceptance Criteria:**
``` 
 Orders will have the following:

- order ID
- Customer ID
- Product ID
Given there is not a model
When the model is done
Then there will be a table in the DB representing the model
```

**Comment by knp319** [comment]
Create a models.py file to hold your model definitions of your resource
