### ISSUE TITLE
Create order

### ISSUE THREAD

**Issue by knp319** [NYU-Devops-orders/orders#4]
**As a** customer
**I need** to be able to order something.
**So that** I can purchase products.

**Assumptions:**
* each order will have the product, quantity and price for each item requested that are connected to a customer id

**Acceptance Criteria:**
```
Given a customer places a new order
When we receive the order details
Then we can share this information with other working teams to ensure the items ship
```

**Comment by knp319** [comment]
This seems like an important issue we should address first

**Comment by pratyush-playground** [comment]
I agree

**Comment by krp391** [comment]
So I changed the name, anyone know why it's not showing up on the Kanban board?
