### ISSUE TITLE
Create a Python Flask Cloud Foundry application in IBM Cloud

### ISSUE THREAD

**Issue by knp319** [NYU-Devops-orders/orders#57]
**As a** developer
**I need** Python Flask Cloud Foundry application
**So that** to execute code and improve our product

**Assumptions:**
* we all have access to IBM cloud
**Acceptance Criteria:**
```
Given ... a desire to consolidate code in one foundry
When ... our team works together 
Then .. we all need access to the application
```

**Comment by krp391** [comment]
Reviewed Kiril's app and confirm it is running.
